repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: ["-L=ndoes,nd,clen"] # 2x words that are preceeded with "\n"; cLen
        exclude: (package.*\.json$|go\.sum|pkg/api/gen)
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fumpt
        exclude: (^pkg/api/gen/.*$|^internal/client/graphql/query/generated.go$)
      - id: go-build-mod
      - id: go-mod-tidy
      - id: go-revive-repo-mod
      - id: go-staticcheck-mod
        exclude: (^expect/.*$|^internal/client/graphql/query/generated.go$)
      - id: go-sec-repo-mod
        args: ["-exclude=G204,G304,G404", "-exclude-generated"]
