version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1
    # image: jaeger-badger:latest
    platform: linux/amd64
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      # SPAN_STORAGE_TYPE: badger
      # BADGER_EPHEMERAL: false
      # BADGER_DIRECTORY_VALUE: /var/badger/data
      # BADGER_DIRECTORY_KEY: /var/badger/key
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
